# TODO: apparently Elixir should do some autoloading magic, which isn't working
# for me (hence the calls to Code.require_file/2)
Code.require_file("u.ex", "lib")
Code.require_file("test_helper.ex", "test")
Code.require_file("cell.ex", "lib/conway")
Code.require_file("cell_test_suite.ex", "test/conway")
Code.require_file("grid.ex", "lib/conway")
Code.require_file("grid_test_suite.ex", "test/conway")
Code.require_file("test_suite.ex", "test/conway")
Code.require_file("cli.ex", "lib/conway")
