Code.require_file("u.ex", "lib")
Code.require_file("test_helper.ex", "lib")
Code.require_file("cell.ex", "lib/conway")
Code.require_file("cell_test_suite.ex", "lib/conway")
Code.require_file("grid.ex", "lib/conway")
Code.require_file("grid_test_suite.ex", "lib/conway")
Code.require_file("test_suite.ex", "lib/conway")
Code.require_file("cli.ex", "lib/conway")
